home:
    resource: "@HomeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

Home:
    path: '/welcome'
    defaults: {_controller:AppBundle\Controller\WelcomeRandomMessageController:RadomMessageAction}